config/routes.rb
Rails.application.routes.draw do
  resources :images

  get 'static_pages/home'

  root 'images#index'
   get 'home', to: 'static_pages#home'

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [ :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to root_path, notice: 'Image was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to root_path, notice: 'Image was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:id, :link, :altText, :captionText, :possition, :right, :textAlign, :maxWidth, :top, :marginLeft, :live)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @images = Image.order(possition: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :altText %><br>
    <%= f.text_field :altText %>
  </div>
  <div class="field">
    <%= f.label :captionText %><br>
    <%= f.text_area :captionText %>
  </div>
  <div class="field">
    <%= f.label :possition %><br>
    <%= f.number_field :possition %>
  </div>
  <div class="field">
    <%= f.label :right %><br>
    <%= f.number_field :right %>
  </div>
  <div class="field">
    <%= f.label :textAlign %><br>
    <%= f.text_field :textAlign %>
  </div>
  <div class="field">
    <%= f.label :maxWidth %><br>
    <%= f.number_field :maxWidth %>
  </div>
  <div class="field">
    <%= f.label :top %><br>
    <%= f.number_field :top %>
  </div>
  <div class="field">
    <%= f.label :marginLeft %><br>
    <%= f.number_field :marginLeft %>
  </div>
  <div class="field">
    <%= f.label :live %><br>
    <%= f.check_box :live %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>


<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>image</th>
      <th>Alttext</th>
      <th>Captiontext</th>
      <th>Possition</th>
      <th>Right</th>
      <th>Textalign</th>
      <th>Maxwidth</th>
      <th>Top</th>
      <th>Marginleft</th>
      <th>Live</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.id %></td>
        <td><%= image_tag image.link, width: '40', height: '30'  %></td>
        <td><%= image.altText %></td>
        <td><%= image.captionText %></td>
        <td><%= image.possition %></td>
        <td><%= image.right %></td>
        <td><%= image.textAlign %></td>
        <td><%= image.maxWidth %></td>
        <td><%= image.top %></td>
        <td><%= image.marginLeft %></td>
        <td><%= image.live %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"

    title TaxworldCoUk

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags 

  body
    .container
      .pull-right.hidden-xs
        = link_to 'https://www.linkedin.com/company/taxworld-ltd', class: "btn btn-circle" do %
          .fa-stack.fa-lg
            i.fa.fa-circle.fa-stack-2x.fa-taxworld-bg
            i.fa.fa-linkedin.fa-stack-1x.fa-taxworld-icon
        = link_to 'https://twitter.com/Taxworlduk', class: "btn btn-circle" do %     
          .fa-stack.fa-lg
            i.fa.fa-circle.fa-stack-2x.fa-taxworld-bg
            i.fa.fa-twitter.fa-stack-1x.fa-taxworld-icon
        
    nav.navbar.navbar-inverse.navbar-top
      .container
        .navbar-header
          button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar

        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li = link_to 'Home', home_path
            li = link_to 'Images', root_path 
            
    = yield
      
   
    .navbar.navbar-default.navbar-bottom
      .container
        .pull-right
          p.navbar-text  
            '
            = link_to 'About us'
            '  | 
            = link_to 'Condition of use'
            '  | 
            = link_to 'Privacy policy'
            '  | 
            = link_to 'Refund policy'
            '  | 
                All rights reserved Taxworld Ltd  
            '  | 
            = Time.now.year 
            '

app/views/static_pages/home.html.slim
#full-width-slideshow.carousel.slide.hidden-xs
  ol.carousel-indicators
    - @images.each_with_index do |image, index| 
      - if image.live
        li data-target="#full-width-slideshow" data-slide-to=index
    
  .carousel-inner
    - @images.each do |image|
      - if image.live
        .item
          = image_tag(image.link)
          .carousel-caption
            h4 
              = image.captionText 
  a.carousel-control.left href ="#full-width-slideshow" data-slide="prev"
    .icon-prev
  a.carousel-control.right href ="#full-width-slideshow" data-slide="next"
    .icon-next

h1.visible-xs.text-center
  | When slide show is gone this can come up